version: '3.8'

services:
  fastapi_backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - fastapi_backend

networks:
  app-network:
    driver: bridge
